<script type="text/javascript">


    require([
        'jquery'
    ], function ($) {
        $(document).ready(function () {
            $(".stnc-beon-header .minicart-wrapper .action.showcart").click(function () {
               /* $('.block-header-customer-login').hide();
                $('.search-input-close').removeClass('close-search');
                $('#search').hide();
                $('#search_autocomplete').hide();*/
            });

            $(".stnc-beon-header.page-header .header-shopbar .header-shop-opts .nav-icon-wrapper").click(function () {

              /*  if ($('.block-header-customer-login').attr('aria-expanded') === 'false') {
                    $('.block-header-customer-login').show();
                    $('.block-header-customer-login').attr('aria-expanded', 'true');
                    $('.block-header-customer-login').removeAttr('aria-hidden');
                    $('.search-input-close').removeClass('close-search');
                    $('#search').hide();
                    $('#search_autocomplete').hide();
                    $('#btn-minicart-close').click();
                    $('.block-header-customer-login .login-form-mini #email').focus();
                } else {
                    $('.block-header-customer-login').hide();
                    $('.block-header-customer-login').attr('aria-expanded', 'false');
                    $('.block-header-customer-login').attr('aria-hidden', 'true');
                }*/
            });
        });
    });
</script>